"""baseline

Revision ID: 6c5cb28282ae
Revises: 
Create Date: 2026-09-15 21:28:11.067209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c5cb28282ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yayasan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yayasan',
    sa.Column('id_yayasan', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama_yayasan', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('no_hp', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('jam_operasional', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tanggal_diperbarui', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_yayasan', name=op.f('yayasan_pkey'))
    )
    # ### end Alembic commands ###
