"""scan_pending dan kode_ml

Revision ID: 8f60781b182f
Revises: 6c5cb28282ae
Create Date: 2026-10-03 16:13:53.591116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f60781b182f'
down_revision: Union[str, Sequence[str], None] = '6c5cb28282ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_pending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=True, comment='Opsional, kalau IoT & ML sepakat satu ID'),
    sa.Column('nik', sa.CHAR(length=16), nullable=True),
    sa.Column('berat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jenis_terdeteksi', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('menunggu', 'selesai', 'kadaluarsa', 'butuh_review', name='statusscan'), nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id_transaksi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_pending_machine_id'), 'scan_pending', ['machine_id'], unique=False)
    op.create_index(op.f('ix_scan_pending_scan_id'), 'scan_pending', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_pending_status'), 'scan_pending', ['status'], unique=False)
    op.drop_table('yayasan')
    op.add_column('data_iot', sa.Column('id_detail', sa.Integer(), nullable=True))
    op.add_column('data_iot', sa.Column('foto_url', sa.String(length=255), nullable=True, comment='URL foto hasil capture kamera IoT'))
    op.create_foreign_key(None, 'data_iot', 'detail_transaksi', ['id_detail'], ['id_detail'])
    op.add_column('detail_transaksi', sa.Column('ditambahkan_manual', sa.Boolean(), nullable=False))
    op.add_column('detail_transaksi', sa.Column('dikoreksi_oleh', sa.String(length=50), nullable=True))
    op.add_column('detail_transaksi', sa.Column('dikoreksi_at', sa.DateTime(), nullable=True))
    op.add_column('jenis_sampah', sa.Column('kode_ml', sa.String(length=50), nullable=True, comment='Label dari model ML, contoh: metal_can'))
    op.create_unique_constraint(None, 'jenis_sampah', ['kode_ml'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jenis_sampah', type_='unique')
    op.drop_column('jenis_sampah', 'kode_ml')
    op.drop_column('detail_transaksi', 'dikoreksi_at')
    op.drop_column('detail_transaksi', 'dikoreksi_oleh')
    op.drop_column('detail_transaksi', 'ditambahkan_manual')
    op.drop_constraint(None, 'data_iot', type_='foreignkey')
    op.drop_column('data_iot', 'foto_url')
    op.drop_column('data_iot', 'id_detail')
    op.create_table('yayasan',
    sa.Column('id_yayasan', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama_yayasan', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('no_hp', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('jam_operasional', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('tanggal_diperbarui', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_yayasan', name=op.f('yayasan_pkey'))
    )
    op.drop_index(op.f('ix_scan_pending_status'), table_name='scan_pending')
    op.drop_index(op.f('ix_scan_pending_scan_id'), table_name='scan_pending')
    op.drop_index(op.f('ix_scan_pending_machine_id'), table_name='scan_pending')
    op.drop_table('scan_pending')
    # ### end Alembic commands ###
